/*
 * elepay API リファレンス
 * elepay APIはRESTをベースに構成された決済APIです。支払い処理、返金処理など、決済に関わる運用における様々なことができます。
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: support@elestyle.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.elepay.client.charge.api;

import io.elepay.client.charge.ApiException;
import io.elepay.client.charge.pojo.CodePaymentMethodResponse;
import org.junit.Test;
import org.junit.Ignore;
import org.junit.Assert;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CodeSettingApi
 */
@Ignore
public class CodeSettingApiTest {

    private final CodeSettingApi api = new CodeSettingApi();

    /**
     * List all enabled EasyQR payment methods
     *
     * EasyQR利用できる決済方法を取得します。
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listCodePaymentMethodsTest() throws ApiException {
        CodePaymentMethodResponse response = api.listCodePaymentMethods();

        // TODO: test validations
    }
}
