/*
 * elepay API リファレンス
 * elepay APIはRESTをベースに構成された決済APIです。支払い処理、返金処理など、決済に関わる運用における様々なことができます。
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: support@elestyle.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.elepay.client.charge.api;

import io.elepay.client.charge.ApiException;
import io.elepay.client.charge.pojo.SubscriptionDto;
import io.elepay.client.charge.pojo.SubscriptionPeriodsResponse;
import io.elepay.client.charge.pojo.SubscriptionReq;
import io.elepay.client.charge.pojo.SubscriptionStatusType;
import io.elepay.client.charge.pojo.SubscriptionUpdateReq;
import io.elepay.client.charge.pojo.SubscriptionsResponse;
import org.junit.Test;
import org.junit.Ignore;
import org.junit.Assert;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SubscriptionApi
 */
@Ignore
public class SubscriptionApiTest {

    private final SubscriptionApi api = new SubscriptionApi();

    /**
     * Cancel subscription
     *
     * 定期課金をキャンセルし、現在の周期の終了日をもって定期課金を終了させます。 キャンセルした定期課金は再スタートできません。 処理中の定期課金はキャンセルできません。 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void cancelSubscriptionTest() throws ApiException {
        String subscriptionId = null;
        SubscriptionDto response = api.cancelSubscription(subscriptionId);

        // TODO: test validations
    }
    /**
     * Create subscription
     *
     * 定期課金を作成します。
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createSubscriptionTest() throws ApiException {
        SubscriptionReq subscriptionReq = null;
        SubscriptionDto response = api.createSubscription(subscriptionReq);

        // TODO: test validations
    }
    /**
     * List subscription periods
     *
     * 定期課金の周期情報をリストで取得します。
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listSubscriptionPeriodsTest() throws ApiException {
        String subscriptionId = null;
        Integer limit = null;
        Integer offset = null;
        SubscriptionPeriodsResponse response = api.listSubscriptionPeriods(subscriptionId, limit, offset);

        // TODO: test validations
    }
    /**
     * List subscriptions
     *
     * 定期課金を一覧で取得します。
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listSubscriptionsTest() throws ApiException {
        String customerId = null;
        Long from = null;
        Long to = null;
        SubscriptionStatusType status = null;
        Integer limit = null;
        Integer offset = null;
        SubscriptionsResponse response = api.listSubscriptions(customerId, from, to, status, limit, offset);

        // TODO: test validations
    }
    /**
     * Resume subscription
     *
     * 延滞中(status&#x3D;past_due)の定期課金を再開させます。 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void resumeSubscriptionTest() throws ApiException {
        String subscriptionId = null;
        SubscriptionDto response = api.resumeSubscription(subscriptionId);

        // TODO: test validations
    }
    /**
     * Retrieve subscription
     *
     * 定期課金情報を取得します。
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void retrieveSubscriptionTest() throws ApiException {
        String subscriptionId = null;
        SubscriptionDto response = api.retrieveSubscription(subscriptionId);

        // TODO: test validations
    }
    /**
     * Start subscription
     *
     * 新規(status&#x3D;new)の定期課金を開始させます。 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void startSubscriptionTest() throws ApiException {
        String subscriptionId = null;
        SubscriptionDto response = api.startSubscription(subscriptionId);

        // TODO: test validations
    }
    /**
     * Update subscription
     *
     * 定期課金を更新します。
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateSubscriptionTest() throws ApiException {
        String subscriptionId = null;
        SubscriptionUpdateReq subscriptionUpdateReq = null;
        SubscriptionDto response = api.updateSubscription(subscriptionId, subscriptionUpdateReq);

        // TODO: test validations
    }
}
