/*
 * elepay API リファレンス
 * elepay APIはRESTをベースに構成された決済APIです。支払い処理、返金処理など、決済に関わる運用における様々なことができます。
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: support@elestyle.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.elepay.client.charge.api;

import io.elepay.client.charge.ApiException;
import io.elepay.client.charge.pojo.LocationsResponse;
import io.elepay.client.charge.pojo.TerminalReaderDto;
import io.elepay.client.charge.pojo.TerminalReaderReq;
import io.elepay.client.charge.pojo.TerminalReadersResponse;
import org.junit.Test;
import org.junit.Ignore;
import org.junit.Assert;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TerminalApi
 */
@Ignore
public class TerminalApiTest {

    private final TerminalApi api = new TerminalApi();

    /**
     * Create terminal reader
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createReaderTest() throws ApiException {
        TerminalReaderReq terminalReaderReq = null;
        TerminalReaderDto response = api.createReader(terminalReaderReq);

        // TODO: test validations
    }
    /**
     * Delete reader
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteReaderTest() throws ApiException {
        String readerId = null;
        api.deleteReader(readerId);

        // TODO: test validations
    }
    /**
     * Get reader
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getReaderTest() throws ApiException {
        String readerId = null;
        TerminalReaderDto response = api.getReader(readerId);

        // TODO: test validations
    }
    /**
     * List locations
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listLocationsTest() throws ApiException {
        LocationsResponse response = api.listLocations();

        // TODO: test validations
    }
    /**
     * List readers
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listReadersTest() throws ApiException {
        Integer limit = null;
        Integer offset = null;
        TerminalReadersResponse response = api.listReaders(limit, offset);

        // TODO: test validations
    }
}
