/*
 * elepay API リファレンス
 * elepay APIはRESTをベースに構成された決済APIです。支払い処理、返金処理など、決済に関わる運用における様々なことができます。
 *
 * The version of the OpenAPI document: 1.2.5
 * Contact: support@elestyle.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.elepay.client.charge.pojo;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.elepay.client.charge.pojo.ResourceWebEnvType;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * 決済方法関する情報
 */
@JsonPropertyOrder({
  ChannelPropertiesDto.JSON_PROPERTY_IS_SUPPORT_REFUND,
  ChannelPropertiesDto.JSON_PROPERTY_IS_SUPPORT_PARTIAL_REFUND,
  ChannelPropertiesDto.JSON_PROPERTY_IS_SUPPORT_MULTIPLE_REFUND,
  ChannelPropertiesDto.JSON_PROPERTY_IS_SUPPORT_SOURCE,
  ChannelPropertiesDto.JSON_PROPERTY_IS_SUPPORT_MULTIPLE_SOURCE,
  ChannelPropertiesDto.JSON_PROPERTY_MAX_AMOUNT,
  ChannelPropertiesDto.JSON_PROPERTY_MIN_AMOUNT,
  ChannelPropertiesDto.JSON_PROPERTY_RESOURCE_WEB_ENV
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ChannelPropertiesDto {
  public static final String JSON_PROPERTY_IS_SUPPORT_REFUND = "isSupportRefund";
  private Boolean isSupportRefund;

  public static final String JSON_PROPERTY_IS_SUPPORT_PARTIAL_REFUND = "isSupportPartialRefund";
  private Boolean isSupportPartialRefund;

  public static final String JSON_PROPERTY_IS_SUPPORT_MULTIPLE_REFUND = "isSupportMultipleRefund";
  private Boolean isSupportMultipleRefund;

  public static final String JSON_PROPERTY_IS_SUPPORT_SOURCE = "isSupportSource";
  private Boolean isSupportSource;

  public static final String JSON_PROPERTY_IS_SUPPORT_MULTIPLE_SOURCE = "isSupportMultipleSource";
  private Boolean isSupportMultipleSource;

  public static final String JSON_PROPERTY_MAX_AMOUNT = "maxAmount";
  private Integer maxAmount;

  public static final String JSON_PROPERTY_MIN_AMOUNT = "minAmount";
  private Integer minAmount;

  public static final String JSON_PROPERTY_RESOURCE_WEB_ENV = "resourceWebEnv";
  private ResourceWebEnvType resourceWebEnv;

  public ChannelPropertiesDto() {
  }

  public ChannelPropertiesDto isSupportRefund(Boolean isSupportRefund) {
    
    this.isSupportRefund = isSupportRefund;
    return this;
  }

   /**
   * 返金 true 利用可能 false 利用不可
   * @return isSupportRefund
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_SUPPORT_REFUND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsSupportRefund() {
    return isSupportRefund;
  }


  @JsonProperty(JSON_PROPERTY_IS_SUPPORT_REFUND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsSupportRefund(Boolean isSupportRefund) {
    this.isSupportRefund = isSupportRefund;
  }


  public ChannelPropertiesDto isSupportPartialRefund(Boolean isSupportPartialRefund) {
    
    this.isSupportPartialRefund = isSupportPartialRefund;
    return this;
  }

   /**
   * 一部返金 true 利用可能 false 利用不可
   * @return isSupportPartialRefund
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_SUPPORT_PARTIAL_REFUND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsSupportPartialRefund() {
    return isSupportPartialRefund;
  }


  @JsonProperty(JSON_PROPERTY_IS_SUPPORT_PARTIAL_REFUND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsSupportPartialRefund(Boolean isSupportPartialRefund) {
    this.isSupportPartialRefund = isSupportPartialRefund;
  }


  public ChannelPropertiesDto isSupportMultipleRefund(Boolean isSupportMultipleRefund) {
    
    this.isSupportMultipleRefund = isSupportMultipleRefund;
    return this;
  }

   /**
   * 複数回返金 true 利用可能 false 一回のみ
   * @return isSupportMultipleRefund
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_SUPPORT_MULTIPLE_REFUND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsSupportMultipleRefund() {
    return isSupportMultipleRefund;
  }


  @JsonProperty(JSON_PROPERTY_IS_SUPPORT_MULTIPLE_REFUND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsSupportMultipleRefund(Boolean isSupportMultipleRefund) {
    this.isSupportMultipleRefund = isSupportMultipleRefund;
  }


  public ChannelPropertiesDto isSupportSource(Boolean isSupportSource) {
    
    this.isSupportSource = isSupportSource;
    return this;
  }

   /**
   * カスタマ機能とソース true 利用可能 false 利用不可
   * @return isSupportSource
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_SUPPORT_SOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsSupportSource() {
    return isSupportSource;
  }


  @JsonProperty(JSON_PROPERTY_IS_SUPPORT_SOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsSupportSource(Boolean isSupportSource) {
    this.isSupportSource = isSupportSource;
  }


  public ChannelPropertiesDto isSupportMultipleSource(Boolean isSupportMultipleSource) {
    
    this.isSupportMultipleSource = isSupportMultipleSource;
    return this;
  }

   /**
   * 複数ソース true バインディング可能 false バインディング不可
   * @return isSupportMultipleSource
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_SUPPORT_MULTIPLE_SOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsSupportMultipleSource() {
    return isSupportMultipleSource;
  }


  @JsonProperty(JSON_PROPERTY_IS_SUPPORT_MULTIPLE_SOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsSupportMultipleSource(Boolean isSupportMultipleSource) {
    this.isSupportMultipleSource = isSupportMultipleSource;
  }


  public ChannelPropertiesDto maxAmount(Integer maxAmount) {
    
    this.maxAmount = maxAmount;
    return this;
  }

   /**
   * 最大可能金額
   * @return maxAmount
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MAX_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMaxAmount() {
    return maxAmount;
  }


  @JsonProperty(JSON_PROPERTY_MAX_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaxAmount(Integer maxAmount) {
    this.maxAmount = maxAmount;
  }


  public ChannelPropertiesDto minAmount(Integer minAmount) {
    
    this.minAmount = minAmount;
    return this;
  }

   /**
   * 最小可能金額
   * @return minAmount
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MIN_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMinAmount() {
    return minAmount;
  }


  @JsonProperty(JSON_PROPERTY_MIN_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMinAmount(Integer minAmount) {
    this.minAmount = minAmount;
  }


  public ChannelPropertiesDto resourceWebEnv(ResourceWebEnvType resourceWebEnv) {
    
    this.resourceWebEnv = resourceWebEnv;
    return this;
  }

   /**
   * Get resourceWebEnv
   * @return resourceWebEnv
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESOURCE_WEB_ENV)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ResourceWebEnvType getResourceWebEnv() {
    return resourceWebEnv;
  }


  @JsonProperty(JSON_PROPERTY_RESOURCE_WEB_ENV)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResourceWebEnv(ResourceWebEnvType resourceWebEnv) {
    this.resourceWebEnv = resourceWebEnv;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChannelPropertiesDto channelPropertiesDto = (ChannelPropertiesDto) o;
    return Objects.equals(this.isSupportRefund, channelPropertiesDto.isSupportRefund) &&
        Objects.equals(this.isSupportPartialRefund, channelPropertiesDto.isSupportPartialRefund) &&
        Objects.equals(this.isSupportMultipleRefund, channelPropertiesDto.isSupportMultipleRefund) &&
        Objects.equals(this.isSupportSource, channelPropertiesDto.isSupportSource) &&
        Objects.equals(this.isSupportMultipleSource, channelPropertiesDto.isSupportMultipleSource) &&
        Objects.equals(this.maxAmount, channelPropertiesDto.maxAmount) &&
        Objects.equals(this.minAmount, channelPropertiesDto.minAmount) &&
        Objects.equals(this.resourceWebEnv, channelPropertiesDto.resourceWebEnv);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isSupportRefund, isSupportPartialRefund, isSupportMultipleRefund, isSupportSource, isSupportMultipleSource, maxAmount, minAmount, resourceWebEnv);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChannelPropertiesDto {\n");
    sb.append("    isSupportRefund: ").append(toIndentedString(isSupportRefund)).append("\n");
    sb.append("    isSupportPartialRefund: ").append(toIndentedString(isSupportPartialRefund)).append("\n");
    sb.append("    isSupportMultipleRefund: ").append(toIndentedString(isSupportMultipleRefund)).append("\n");
    sb.append("    isSupportSource: ").append(toIndentedString(isSupportSource)).append("\n");
    sb.append("    isSupportMultipleSource: ").append(toIndentedString(isSupportMultipleSource)).append("\n");
    sb.append("    maxAmount: ").append(toIndentedString(maxAmount)).append("\n");
    sb.append("    minAmount: ").append(toIndentedString(minAmount)).append("\n");
    sb.append("    resourceWebEnv: ").append(toIndentedString(resourceWebEnv)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `isSupportRefund` to the URL query string
    if (getIsSupportRefund() != null) {
      try {
        joiner.add(String.format("%sisSupportRefund%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getIsSupportRefund()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `isSupportPartialRefund` to the URL query string
    if (getIsSupportPartialRefund() != null) {
      try {
        joiner.add(String.format("%sisSupportPartialRefund%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getIsSupportPartialRefund()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `isSupportMultipleRefund` to the URL query string
    if (getIsSupportMultipleRefund() != null) {
      try {
        joiner.add(String.format("%sisSupportMultipleRefund%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getIsSupportMultipleRefund()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `isSupportSource` to the URL query string
    if (getIsSupportSource() != null) {
      try {
        joiner.add(String.format("%sisSupportSource%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getIsSupportSource()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `isSupportMultipleSource` to the URL query string
    if (getIsSupportMultipleSource() != null) {
      try {
        joiner.add(String.format("%sisSupportMultipleSource%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getIsSupportMultipleSource()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `maxAmount` to the URL query string
    if (getMaxAmount() != null) {
      try {
        joiner.add(String.format("%smaxAmount%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getMaxAmount()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `minAmount` to the URL query string
    if (getMinAmount() != null) {
      try {
        joiner.add(String.format("%sminAmount%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getMinAmount()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `resourceWebEnv` to the URL query string
    if (getResourceWebEnv() != null) {
      try {
        joiner.add(String.format("%sresourceWebEnv%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getResourceWebEnv()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    return joiner.toString();
  }

}

