/*
 * elepay API リファレンス
 * elepay APIはRESTをベースに構成された決済APIです。支払い処理、返金処理など、決済に関わる運用における様々なことができます。
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: support@elestyle.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.elepay.client.charge.pojo;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.elepay.client.charge.pojo.ChargeDto;
import io.elepay.client.charge.pojo.CodeItem;
import io.elepay.client.charge.pojo.CustomerDto;
import io.elepay.client.charge.pojo.InvoiceDto;
import io.elepay.client.charge.pojo.SourceDto;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * EasyQRコードオブジェクト
 */
@JsonPropertyOrder({
  CodeDto.JSON_PROPERTY_ID,
  CodeDto.JSON_PROPERTY_OBJECT,
  CodeDto.JSON_PROPERTY_LIVE_MODE,
  CodeDto.JSON_PROPERTY_CODE_URL,
  CodeDto.JSON_PROPERTY_AMOUNT,
  CodeDto.JSON_PROPERTY_CURRENCY,
  CodeDto.JSON_PROPERTY_ORDER_NO,
  CodeDto.JSON_PROPERTY_DESCRIPTION,
  CodeDto.JSON_PROPERTY_EXTRA,
  CodeDto.JSON_PROPERTY_METADATA,
  CodeDto.JSON_PROPERTY_STATUS,
  CodeDto.JSON_PROPERTY_CHARGE,
  CodeDto.JSON_PROPERTY_CUSTOMER,
  CodeDto.JSON_PROPERTY_SOURCE,
  CodeDto.JSON_PROPERTY_FRONT_URL,
  CodeDto.JSON_PROPERTY_ITEMS,
  CodeDto.JSON_PROPERTY_LOCATION_ID,
  CodeDto.JSON_PROPERTY_EXPIRED,
  CodeDto.JSON_PROPERTY_EXPIRY_TIME,
  CodeDto.JSON_PROPERTY_EXPIRY_PERIOD,
  CodeDto.JSON_PROPERTY_CREATE_TIME,
  CodeDto.JSON_PROPERTY_SHOULD_CREATE_SOURCE,
  CodeDto.JSON_PROPERTY_ACTIVE_SOURCES,
  CodeDto.JSON_PROPERTY_INVOICE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class CodeDto {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_OBJECT = "object";
  private String _object = "code";

  public static final String JSON_PROPERTY_LIVE_MODE = "liveMode";
  private Boolean liveMode;

  public static final String JSON_PROPERTY_CODE_URL = "codeUrl";
  private String codeUrl;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  private Integer amount;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  private String currency = "JPY";

  public static final String JSON_PROPERTY_ORDER_NO = "orderNo";
  private String orderNo;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_EXTRA = "extra";
  private Map<String, String> extra = new HashMap<>();

  public static final String JSON_PROPERTY_METADATA = "metadata";
  private Map<String, String> metadata = new HashMap<>();

  public static final String JSON_PROPERTY_STATUS = "status";
  private String status;

  public static final String JSON_PROPERTY_CHARGE = "charge";
  private ChargeDto charge;

  public static final String JSON_PROPERTY_CUSTOMER = "customer";
  private CustomerDto customer;

  public static final String JSON_PROPERTY_SOURCE = "source";
  private SourceDto source;

  public static final String JSON_PROPERTY_FRONT_URL = "frontUrl";
  private String frontUrl;

  public static final String JSON_PROPERTY_ITEMS = "items";
  private List<CodeItem> items;

  public static final String JSON_PROPERTY_LOCATION_ID = "locationId";
  private String locationId;

  public static final String JSON_PROPERTY_EXPIRED = "expired";
  private Boolean expired;

  public static final String JSON_PROPERTY_EXPIRY_TIME = "expiryTime";
  private Long expiryTime;

  public static final String JSON_PROPERTY_EXPIRY_PERIOD = "expiryPeriod";
  private Long expiryPeriod;

  public static final String JSON_PROPERTY_CREATE_TIME = "createTime";
  private Long createTime;

  public static final String JSON_PROPERTY_SHOULD_CREATE_SOURCE = "shouldCreateSource";
  private Boolean shouldCreateSource;

  public static final String JSON_PROPERTY_ACTIVE_SOURCES = "activeSources";
  private List<SourceDto> activeSources;

  public static final String JSON_PROPERTY_INVOICE = "invoice";
  private InvoiceDto invoice;

  public CodeDto() {
  }

  public CodeDto id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * EasyQRコードID
   * @return id
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public CodeDto _object(String _object) {
    
    this._object = _object;
    return this;
  }

   /**
   * 対象種類の表記
   * @return _object
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OBJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getObject() {
    return _object;
  }


  @JsonProperty(JSON_PROPERTY_OBJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setObject(String _object) {
    this._object = _object;
  }


  public CodeDto liveMode(Boolean liveMode) {
    
    this.liveMode = liveMode;
    return this;
  }

   /**
   * 本番モードかどうか - false テストモード - true 本番モード 
   * @return liveMode
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LIVE_MODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getLiveMode() {
    return liveMode;
  }


  @JsonProperty(JSON_PROPERTY_LIVE_MODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLiveMode(Boolean liveMode) {
    this.liveMode = liveMode;
  }


  public CodeDto codeUrl(String codeUrl) {
    
    this.codeUrl = codeUrl;
    return this;
  }

   /**
   * EasyQRコードURL
   * @return codeUrl
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CODE_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCodeUrl() {
    return codeUrl;
  }


  @JsonProperty(JSON_PROPERTY_CODE_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCodeUrl(String codeUrl) {
    this.codeUrl = codeUrl;
  }


  public CodeDto amount(Integer amount) {
    
    this.amount = amount;
    return this;
  }

   /**
   * 支払い金額
   * @return amount
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAmount() {
    return amount;
  }


  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAmount(Integer amount) {
    this.amount = amount;
  }


  public CodeDto currency(String currency) {
    
    this.currency = currency;
    return this;
  }

   /**
   * 通貨コード (ISO_4217)
   * @return currency
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCurrency() {
    return currency;
  }


  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCurrency(String currency) {
    this.currency = currency;
  }


  public CodeDto orderNo(String orderNo) {
    
    this.orderNo = orderNo;
    return this;
  }

   /**
   * お客様システム側のオーダーNo、例えば注文番号、決済IDなど
   * @return orderNo
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ORDER_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOrderNo() {
    return orderNo;
  }


  @JsonProperty(JSON_PROPERTY_ORDER_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrderNo(String orderNo) {
    this.orderNo = orderNo;
  }


  public CodeDto description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * 支払いオブジェクトの「決済に関する説明」
   * @return description
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(String description) {
    this.description = description;
  }


  public CodeDto extra(Map<String, String> extra) {
    
    this.extra = extra;
    return this;
  }

  public CodeDto putExtraItem(String key, String extraItem) {
    if (this.extra == null) {
      this.extra = new HashMap<>();
    }
    this.extra.put(key, extraItem);
    return this;
  }

   /**
   * 支払いエキストラデータ
   * @return extra
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXTRA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, String> getExtra() {
    return extra;
  }


  @JsonProperty(JSON_PROPERTY_EXTRA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExtra(Map<String, String> extra) {
    this.extra = extra;
  }


  public CodeDto metadata(Map<String, String> metadata) {
    
    this.metadata = metadata;
    return this;
  }

  public CodeDto putMetadataItem(String key, String metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }

   /**
   * 支払いオブジェクトの「メタデータ」
   * @return metadata
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, String> getMetadata() {
    return metadata;
  }


  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadata(Map<String, String> metadata) {
    this.metadata = metadata;
  }


  public CodeDto status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(String status) {
    this.status = status;
  }


  public CodeDto charge(ChargeDto charge) {
    
    this.charge = charge;
    return this;
  }

   /**
   * Get charge
   * @return charge
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHARGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ChargeDto getCharge() {
    return charge;
  }


  @JsonProperty(JSON_PROPERTY_CHARGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCharge(ChargeDto charge) {
    this.charge = charge;
  }


  public CodeDto customer(CustomerDto customer) {
    
    this.customer = customer;
    return this;
  }

   /**
   * Get customer
   * @return customer
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CUSTOMER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CustomerDto getCustomer() {
    return customer;
  }


  @JsonProperty(JSON_PROPERTY_CUSTOMER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomer(CustomerDto customer) {
    this.customer = customer;
  }


  public CodeDto source(SourceDto source) {
    
    this.source = source;
    return this;
  }

   /**
   * Get source
   * @return source
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SourceDto getSource() {
    return source;
  }


  @JsonProperty(JSON_PROPERTY_SOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSource(SourceDto source) {
    this.source = source;
  }


  public CodeDto frontUrl(String frontUrl) {
    
    this.frontUrl = frontUrl;
    return this;
  }

   /**
   * Get frontUrl
   * @return frontUrl
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FRONT_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFrontUrl() {
    return frontUrl;
  }


  @JsonProperty(JSON_PROPERTY_FRONT_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFrontUrl(String frontUrl) {
    this.frontUrl = frontUrl;
  }


  public CodeDto items(List<CodeItem> items) {
    
    this.items = items;
    return this;
  }

  public CodeDto addItemsItem(CodeItem itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<>();
    }
    this.items.add(itemsItem);
    return this;
  }

   /**
   * Get items
   * @return items
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ITEMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<CodeItem> getItems() {
    return items;
  }


  @JsonProperty(JSON_PROPERTY_ITEMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setItems(List<CodeItem> items) {
    this.items = items;
  }


  public CodeDto locationId(String locationId) {
    
    this.locationId = locationId;
    return this;
  }

   /**
   * ロケーションID
   * @return locationId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLocationId() {
    return locationId;
  }


  @JsonProperty(JSON_PROPERTY_LOCATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocationId(String locationId) {
    this.locationId = locationId;
  }


  public CodeDto expired(Boolean expired) {
    
    this.expired = expired;
    return this;
  }

   /**
   * EasyQRコード有効有無
   * @return expired
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXPIRED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getExpired() {
    return expired;
  }


  @JsonProperty(JSON_PROPERTY_EXPIRED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpired(Boolean expired) {
    this.expired = expired;
  }


  public CodeDto expiryTime(Long expiryTime) {
    
    this.expiryTime = expiryTime;
    return this;
  }

   /**
   * EasyQRコード有効期限（エポックミリ秒）
   * @return expiryTime
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXPIRY_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getExpiryTime() {
    return expiryTime;
  }


  @JsonProperty(JSON_PROPERTY_EXPIRY_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpiryTime(Long expiryTime) {
    this.expiryTime = expiryTime;
  }


  public CodeDto expiryPeriod(Long expiryPeriod) {
    
    this.expiryPeriod = expiryPeriod;
    return this;
  }

   /**
   * EasyQRコード有効期限までの残りミリ秒数
   * @return expiryPeriod
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXPIRY_PERIOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getExpiryPeriod() {
    return expiryPeriod;
  }


  @JsonProperty(JSON_PROPERTY_EXPIRY_PERIOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpiryPeriod(Long expiryPeriod) {
    this.expiryPeriod = expiryPeriod;
  }


  public CodeDto createTime(Long createTime) {
    
    this.createTime = createTime;
    return this;
  }

   /**
   * コード新規時間（エポックミリ秒）
   * @return createTime
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getCreateTime() {
    return createTime;
  }


  @JsonProperty(JSON_PROPERTY_CREATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreateTime(Long createTime) {
    this.createTime = createTime;
  }


  public CodeDto shouldCreateSource(Boolean shouldCreateSource) {
    
    this.shouldCreateSource = shouldCreateSource;
    return this;
  }

   /**
   * このコードで新しいカスタマソースを作成する必要があるかどうか。 
   * @return shouldCreateSource
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SHOULD_CREATE_SOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getShouldCreateSource() {
    return shouldCreateSource;
  }


  @JsonProperty(JSON_PROPERTY_SHOULD_CREATE_SOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShouldCreateSource(Boolean shouldCreateSource) {
    this.shouldCreateSource = shouldCreateSource;
  }


  public CodeDto activeSources(List<SourceDto> activeSources) {
    
    this.activeSources = activeSources;
    return this;
  }

  public CodeDto addActiveSourcesItem(SourceDto activeSourcesItem) {
    if (this.activeSources == null) {
      this.activeSources = new ArrayList<>();
    }
    this.activeSources.add(activeSourcesItem);
    return this;
  }

   /**
   * 有効なカスタマソースリスト
   * @return activeSources
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACTIVE_SOURCES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<SourceDto> getActiveSources() {
    return activeSources;
  }


  @JsonProperty(JSON_PROPERTY_ACTIVE_SOURCES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActiveSources(List<SourceDto> activeSources) {
    this.activeSources = activeSources;
  }


  public CodeDto invoice(InvoiceDto invoice) {
    
    this.invoice = invoice;
    return this;
  }

   /**
   * Get invoice
   * @return invoice
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INVOICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public InvoiceDto getInvoice() {
    return invoice;
  }


  @JsonProperty(JSON_PROPERTY_INVOICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInvoice(InvoiceDto invoice) {
    this.invoice = invoice;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CodeDto codeDto = (CodeDto) o;
    return Objects.equals(this.id, codeDto.id) &&
        Objects.equals(this._object, codeDto._object) &&
        Objects.equals(this.liveMode, codeDto.liveMode) &&
        Objects.equals(this.codeUrl, codeDto.codeUrl) &&
        Objects.equals(this.amount, codeDto.amount) &&
        Objects.equals(this.currency, codeDto.currency) &&
        Objects.equals(this.orderNo, codeDto.orderNo) &&
        Objects.equals(this.description, codeDto.description) &&
        Objects.equals(this.extra, codeDto.extra) &&
        Objects.equals(this.metadata, codeDto.metadata) &&
        Objects.equals(this.status, codeDto.status) &&
        Objects.equals(this.charge, codeDto.charge) &&
        Objects.equals(this.customer, codeDto.customer) &&
        Objects.equals(this.source, codeDto.source) &&
        Objects.equals(this.frontUrl, codeDto.frontUrl) &&
        Objects.equals(this.items, codeDto.items) &&
        Objects.equals(this.locationId, codeDto.locationId) &&
        Objects.equals(this.expired, codeDto.expired) &&
        Objects.equals(this.expiryTime, codeDto.expiryTime) &&
        Objects.equals(this.expiryPeriod, codeDto.expiryPeriod) &&
        Objects.equals(this.createTime, codeDto.createTime) &&
        Objects.equals(this.shouldCreateSource, codeDto.shouldCreateSource) &&
        Objects.equals(this.activeSources, codeDto.activeSources) &&
        Objects.equals(this.invoice, codeDto.invoice);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, _object, liveMode, codeUrl, amount, currency, orderNo, description, extra, metadata, status, charge, customer, source, frontUrl, items, locationId, expired, expiryTime, expiryPeriod, createTime, shouldCreateSource, activeSources, invoice);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CodeDto {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    _object: ").append(toIndentedString(_object)).append("\n");
    sb.append("    liveMode: ").append(toIndentedString(liveMode)).append("\n");
    sb.append("    codeUrl: ").append(toIndentedString(codeUrl)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    orderNo: ").append(toIndentedString(orderNo)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    extra: ").append(toIndentedString(extra)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    charge: ").append(toIndentedString(charge)).append("\n");
    sb.append("    customer: ").append(toIndentedString(customer)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    frontUrl: ").append(toIndentedString(frontUrl)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("    locationId: ").append(toIndentedString(locationId)).append("\n");
    sb.append("    expired: ").append(toIndentedString(expired)).append("\n");
    sb.append("    expiryTime: ").append(toIndentedString(expiryTime)).append("\n");
    sb.append("    expiryPeriod: ").append(toIndentedString(expiryPeriod)).append("\n");
    sb.append("    createTime: ").append(toIndentedString(createTime)).append("\n");
    sb.append("    shouldCreateSource: ").append(toIndentedString(shouldCreateSource)).append("\n");
    sb.append("    activeSources: ").append(toIndentedString(activeSources)).append("\n");
    sb.append("    invoice: ").append(toIndentedString(invoice)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      try {
        joiner.add(String.format("%sid%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `object` to the URL query string
    if (getObject() != null) {
      try {
        joiner.add(String.format("%sobject%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getObject()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `liveMode` to the URL query string
    if (getLiveMode() != null) {
      try {
        joiner.add(String.format("%sliveMode%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getLiveMode()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `codeUrl` to the URL query string
    if (getCodeUrl() != null) {
      try {
        joiner.add(String.format("%scodeUrl%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCodeUrl()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `amount` to the URL query string
    if (getAmount() != null) {
      try {
        joiner.add(String.format("%samount%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getAmount()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `currency` to the URL query string
    if (getCurrency() != null) {
      try {
        joiner.add(String.format("%scurrency%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCurrency()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `orderNo` to the URL query string
    if (getOrderNo() != null) {
      try {
        joiner.add(String.format("%sorderNo%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getOrderNo()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `description` to the URL query string
    if (getDescription() != null) {
      try {
        joiner.add(String.format("%sdescription%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getDescription()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `extra` to the URL query string
    if (getExtra() != null) {
      for (String _key : getExtra().keySet()) {
        try {
          joiner.add(String.format("%sextra%s%s=%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, _key, containerSuffix),
              getExtra().get(_key), URLEncoder.encode(String.valueOf(getExtra().get(_key)), "UTF-8").replaceAll("\\+", "%20")));
        } catch (UnsupportedEncodingException e) {
          // Should never happen, UTF-8 is always supported
          throw new RuntimeException(e);
        }
      }
    }

    // add `metadata` to the URL query string
    if (getMetadata() != null) {
      for (String _key : getMetadata().keySet()) {
        try {
          joiner.add(String.format("%smetadata%s%s=%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, _key, containerSuffix),
              getMetadata().get(_key), URLEncoder.encode(String.valueOf(getMetadata().get(_key)), "UTF-8").replaceAll("\\+", "%20")));
        } catch (UnsupportedEncodingException e) {
          // Should never happen, UTF-8 is always supported
          throw new RuntimeException(e);
        }
      }
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      try {
        joiner.add(String.format("%sstatus%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getStatus()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `charge` to the URL query string
    if (getCharge() != null) {
      joiner.add(getCharge().toUrlQueryString(prefix + "charge" + suffix));
    }

    // add `customer` to the URL query string
    if (getCustomer() != null) {
      joiner.add(getCustomer().toUrlQueryString(prefix + "customer" + suffix));
    }

    // add `source` to the URL query string
    if (getSource() != null) {
      joiner.add(getSource().toUrlQueryString(prefix + "source" + suffix));
    }

    // add `frontUrl` to the URL query string
    if (getFrontUrl() != null) {
      try {
        joiner.add(String.format("%sfrontUrl%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getFrontUrl()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `items` to the URL query string
    if (getItems() != null) {
      for (int i = 0; i < getItems().size(); i++) {
        if (getItems().get(i) != null) {
          joiner.add(getItems().get(i).toUrlQueryString(String.format("%sitems%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `locationId` to the URL query string
    if (getLocationId() != null) {
      try {
        joiner.add(String.format("%slocationId%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getLocationId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `expired` to the URL query string
    if (getExpired() != null) {
      try {
        joiner.add(String.format("%sexpired%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getExpired()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `expiryTime` to the URL query string
    if (getExpiryTime() != null) {
      try {
        joiner.add(String.format("%sexpiryTime%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getExpiryTime()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `expiryPeriod` to the URL query string
    if (getExpiryPeriod() != null) {
      try {
        joiner.add(String.format("%sexpiryPeriod%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getExpiryPeriod()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `createTime` to the URL query string
    if (getCreateTime() != null) {
      try {
        joiner.add(String.format("%screateTime%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCreateTime()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `shouldCreateSource` to the URL query string
    if (getShouldCreateSource() != null) {
      try {
        joiner.add(String.format("%sshouldCreateSource%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getShouldCreateSource()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `activeSources` to the URL query string
    if (getActiveSources() != null) {
      for (int i = 0; i < getActiveSources().size(); i++) {
        if (getActiveSources().get(i) != null) {
          joiner.add(getActiveSources().get(i).toUrlQueryString(String.format("%sactiveSources%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `invoice` to the URL query string
    if (getInvoice() != null) {
      joiner.add(getInvoice().toUrlQueryString(prefix + "invoice" + suffix));
    }

    return joiner.toString();
  }

}

