/*
 * elepay API リファレンス
 * elepay APIはRESTをベースに構成された決済APIです。支払い処理、返金処理など、決済に関わる運用における様々なことができます。
 *
 * The version of the OpenAPI document: 1.1.24
 * Contact: support@elestyle.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.elepay.client.charge.pojo;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.elepay.client.charge.pojo.CustomerDto;
import io.elepay.client.charge.pojo.DiscountDto;
import io.elepay.client.charge.pojo.PlanDto;
import io.elepay.client.charge.pojo.SubscriptionScheduleDto;
import io.elepay.client.charge.pojo.SubscriptionStatusType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * 定期課金オブジェクト
 */
@ApiModel(description = "定期課金オブジェクト")
@JsonPropertyOrder({
  SubscriptionDto.JSON_PROPERTY_ID,
  SubscriptionDto.JSON_PROPERTY_APP_ID,
  SubscriptionDto.JSON_PROPERTY_OBJECT,
  SubscriptionDto.JSON_PROPERTY_LIVE_MODE,
  SubscriptionDto.JSON_PROPERTY_CUSTOMER_ID,
  SubscriptionDto.JSON_PROPERTY_CUSTOMER,
  SubscriptionDto.JSON_PROPERTY_PLAN_ID,
  SubscriptionDto.JSON_PROPERTY_PLAN,
  SubscriptionDto.JSON_PROPERTY_CURRENT_SCHEDULE,
  SubscriptionDto.JSON_PROPERTY_PRORATE,
  SubscriptionDto.JSON_PROPERTY_START_TIME,
  SubscriptionDto.JSON_PROPERTY_END_TIME,
  SubscriptionDto.JSON_PROPERTY_NEXT_SCHEDULE_TIME,
  SubscriptionDto.JSON_PROPERTY_TRIAL_START,
  SubscriptionDto.JSON_PROPERTY_TRIAL_END,
  SubscriptionDto.JSON_PROPERTY_DISCOUNT,
  SubscriptionDto.JSON_PROPERTY_METADATA,
  SubscriptionDto.JSON_PROPERTY_STATUS,
  SubscriptionDto.JSON_PROPERTY_CREATE_TIME,
  SubscriptionDto.JSON_PROPERTY_UPDATE_TIME
})

public class SubscriptionDto {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_APP_ID = "appId";
  private String appId;

  public static final String JSON_PROPERTY_OBJECT = "object";
  private String _object = "subscription";

  public static final String JSON_PROPERTY_LIVE_MODE = "liveMode";
  private Boolean liveMode;

  public static final String JSON_PROPERTY_CUSTOMER_ID = "customerId";
  private String customerId;

  public static final String JSON_PROPERTY_CUSTOMER = "customer";
  private CustomerDto customer;

  public static final String JSON_PROPERTY_PLAN_ID = "planId";
  private String planId;

  public static final String JSON_PROPERTY_PLAN = "plan";
  private PlanDto plan;

  public static final String JSON_PROPERTY_CURRENT_SCHEDULE = "currentSchedule";
  private SubscriptionScheduleDto currentSchedule;

  public static final String JSON_PROPERTY_PRORATE = "prorate";
  private Boolean prorate;

  public static final String JSON_PROPERTY_START_TIME = "startTime";
  private Long startTime;

  public static final String JSON_PROPERTY_END_TIME = "endTime";
  private Long endTime;

  public static final String JSON_PROPERTY_NEXT_SCHEDULE_TIME = "nextScheduleTime";
  private Long nextScheduleTime;

  public static final String JSON_PROPERTY_TRIAL_START = "trialStart";
  private Long trialStart;

  public static final String JSON_PROPERTY_TRIAL_END = "trialEnd";
  private Long trialEnd;

  public static final String JSON_PROPERTY_DISCOUNT = "discount";
  private DiscountDto discount;

  public static final String JSON_PROPERTY_METADATA = "metadata";
  private Map<String, String> metadata = null;

  public static final String JSON_PROPERTY_STATUS = "status";
  private SubscriptionStatusType status;

  public static final String JSON_PROPERTY_CREATE_TIME = "createTime";
  private Long createTime;

  public static final String JSON_PROPERTY_UPDATE_TIME = "updateTime";
  private Long updateTime;


  public SubscriptionDto id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Subscription ID
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Subscription ID")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public SubscriptionDto appId(String appId) {
    
    this.appId = appId;
    return this;
  }

   /**
   * App ID
   * @return appId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "App ID")
  @JsonProperty(JSON_PROPERTY_APP_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAppId() {
    return appId;
  }


  public void setAppId(String appId) {
    this.appId = appId;
  }


  public SubscriptionDto _object(String _object) {
    
    this._object = _object;
    return this;
  }

   /**
   * 対象種類の表記
   * @return _object
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "対象種類の表記")
  @JsonProperty(JSON_PROPERTY_OBJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getObject() {
    return _object;
  }


  public void setObject(String _object) {
    this._object = _object;
  }


  public SubscriptionDto liveMode(Boolean liveMode) {
    
    this.liveMode = liveMode;
    return this;
  }

   /**
   * 本番モードかどうか - false テストモード - true 本番モード 
   * @return liveMode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "本番モードかどうか - false テストモード - true 本番モード ")
  @JsonProperty(JSON_PROPERTY_LIVE_MODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getLiveMode() {
    return liveMode;
  }


  public void setLiveMode(Boolean liveMode) {
    this.liveMode = liveMode;
  }


  public SubscriptionDto customerId(String customerId) {
    
    this.customerId = customerId;
    return this;
  }

   /**
   * Customer ID
   * @return customerId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Customer ID")
  @JsonProperty(JSON_PROPERTY_CUSTOMER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCustomerId() {
    return customerId;
  }


  public void setCustomerId(String customerId) {
    this.customerId = customerId;
  }


  public SubscriptionDto customer(CustomerDto customer) {
    
    this.customer = customer;
    return this;
  }

   /**
   * Get customer
   * @return customer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CUSTOMER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CustomerDto getCustomer() {
    return customer;
  }


  public void setCustomer(CustomerDto customer) {
    this.customer = customer;
  }


  public SubscriptionDto planId(String planId) {
    
    this.planId = planId;
    return this;
  }

   /**
   * Plan ID
   * @return planId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Plan ID")
  @JsonProperty(JSON_PROPERTY_PLAN_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPlanId() {
    return planId;
  }


  public void setPlanId(String planId) {
    this.planId = planId;
  }


  public SubscriptionDto plan(PlanDto plan) {
    
    this.plan = plan;
    return this;
  }

   /**
   * Get plan
   * @return plan
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PLAN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PlanDto getPlan() {
    return plan;
  }


  public void setPlan(PlanDto plan) {
    this.plan = plan;
  }


  public SubscriptionDto currentSchedule(SubscriptionScheduleDto currentSchedule) {
    
    this.currentSchedule = currentSchedule;
    return this;
  }

   /**
   * Get currentSchedule
   * @return currentSchedule
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CURRENT_SCHEDULE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SubscriptionScheduleDto getCurrentSchedule() {
    return currentSchedule;
  }


  public void setCurrentSchedule(SubscriptionScheduleDto currentSchedule) {
    this.currentSchedule = currentSchedule;
  }


  public SubscriptionDto prorate(Boolean prorate) {
    
    this.prorate = prorate;
    return this;
  }

   /**
   * 日割り課金が有効かどうか
   * @return prorate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "日割り課金が有効かどうか")
  @JsonProperty(JSON_PROPERTY_PRORATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getProrate() {
    return prorate;
  }


  public void setProrate(Boolean prorate) {
    this.prorate = prorate;
  }


  public SubscriptionDto startTime(Long startTime) {
    
    this.startTime = startTime;
    return this;
  }

   /**
   * 定期課金開始UTCタイムスタンプ
   * @return startTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "定期課金開始UTCタイムスタンプ")
  @JsonProperty(JSON_PROPERTY_START_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getStartTime() {
    return startTime;
  }


  public void setStartTime(Long startTime) {
    this.startTime = startTime;
  }


  public SubscriptionDto endTime(Long endTime) {
    
    this.endTime = endTime;
    return this;
  }

   /**
   * 定期課金終了UTCタイムスタンプ
   * @return endTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "定期課金終了UTCタイムスタンプ")
  @JsonProperty(JSON_PROPERTY_END_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getEndTime() {
    return endTime;
  }


  public void setEndTime(Long endTime) {
    this.endTime = endTime;
  }


  public SubscriptionDto nextScheduleTime(Long nextScheduleTime) {
    
    this.nextScheduleTime = nextScheduleTime;
    return this;
  }

   /**
   * 次定期課金周期開始UTCタイムスタンプ
   * @return nextScheduleTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "次定期課金周期開始UTCタイムスタンプ")
  @JsonProperty(JSON_PROPERTY_NEXT_SCHEDULE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getNextScheduleTime() {
    return nextScheduleTime;
  }


  public void setNextScheduleTime(Long nextScheduleTime) {
    this.nextScheduleTime = nextScheduleTime;
  }


  public SubscriptionDto trialStart(Long trialStart) {
    
    this.trialStart = trialStart;
    return this;
  }

   /**
   * トライアル開始UTCタイムスタンプ
   * @return trialStart
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "トライアル開始UTCタイムスタンプ")
  @JsonProperty(JSON_PROPERTY_TRIAL_START)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTrialStart() {
    return trialStart;
  }


  public void setTrialStart(Long trialStart) {
    this.trialStart = trialStart;
  }


  public SubscriptionDto trialEnd(Long trialEnd) {
    
    this.trialEnd = trialEnd;
    return this;
  }

   /**
   * トライアル終了UTCタイムスタンプ
   * @return trialEnd
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "トライアル終了UTCタイムスタンプ")
  @JsonProperty(JSON_PROPERTY_TRIAL_END)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTrialEnd() {
    return trialEnd;
  }


  public void setTrialEnd(Long trialEnd) {
    this.trialEnd = trialEnd;
  }


  public SubscriptionDto discount(DiscountDto discount) {
    
    this.discount = discount;
    return this;
  }

   /**
   * Get discount
   * @return discount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DISCOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DiscountDto getDiscount() {
    return discount;
  }


  public void setDiscount(DiscountDto discount) {
    this.discount = discount;
  }


  public SubscriptionDto metadata(Map<String, String> metadata) {
    
    this.metadata = metadata;
    return this;
  }

  public SubscriptionDto putMetadataItem(String key, String metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }

   /**
   * メタデータ
   * @return metadata
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "メタデータ")
  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, String> getMetadata() {
    return metadata;
  }


  public void setMetadata(Map<String, String> metadata) {
    this.metadata = metadata;
  }


  public SubscriptionDto status(SubscriptionStatusType status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SubscriptionStatusType getStatus() {
    return status;
  }


  public void setStatus(SubscriptionStatusType status) {
    this.status = status;
  }


  public SubscriptionDto createTime(Long createTime) {
    
    this.createTime = createTime;
    return this;
  }

   /**
   * 作成UTCタイムスタンプ
   * @return createTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "作成UTCタイムスタンプ")
  @JsonProperty(JSON_PROPERTY_CREATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getCreateTime() {
    return createTime;
  }


  public void setCreateTime(Long createTime) {
    this.createTime = createTime;
  }


  public SubscriptionDto updateTime(Long updateTime) {
    
    this.updateTime = updateTime;
    return this;
  }

   /**
   * 更新UTCタイムスタンプ
   * @return updateTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "更新UTCタイムスタンプ")
  @JsonProperty(JSON_PROPERTY_UPDATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getUpdateTime() {
    return updateTime;
  }


  public void setUpdateTime(Long updateTime) {
    this.updateTime = updateTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubscriptionDto subscriptionDto = (SubscriptionDto) o;
    return Objects.equals(this.id, subscriptionDto.id) &&
        Objects.equals(this.appId, subscriptionDto.appId) &&
        Objects.equals(this._object, subscriptionDto._object) &&
        Objects.equals(this.liveMode, subscriptionDto.liveMode) &&
        Objects.equals(this.customerId, subscriptionDto.customerId) &&
        Objects.equals(this.customer, subscriptionDto.customer) &&
        Objects.equals(this.planId, subscriptionDto.planId) &&
        Objects.equals(this.plan, subscriptionDto.plan) &&
        Objects.equals(this.currentSchedule, subscriptionDto.currentSchedule) &&
        Objects.equals(this.prorate, subscriptionDto.prorate) &&
        Objects.equals(this.startTime, subscriptionDto.startTime) &&
        Objects.equals(this.endTime, subscriptionDto.endTime) &&
        Objects.equals(this.nextScheduleTime, subscriptionDto.nextScheduleTime) &&
        Objects.equals(this.trialStart, subscriptionDto.trialStart) &&
        Objects.equals(this.trialEnd, subscriptionDto.trialEnd) &&
        Objects.equals(this.discount, subscriptionDto.discount) &&
        Objects.equals(this.metadata, subscriptionDto.metadata) &&
        Objects.equals(this.status, subscriptionDto.status) &&
        Objects.equals(this.createTime, subscriptionDto.createTime) &&
        Objects.equals(this.updateTime, subscriptionDto.updateTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, appId, _object, liveMode, customerId, customer, planId, plan, currentSchedule, prorate, startTime, endTime, nextScheduleTime, trialStart, trialEnd, discount, metadata, status, createTime, updateTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubscriptionDto {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    appId: ").append(toIndentedString(appId)).append("\n");
    sb.append("    _object: ").append(toIndentedString(_object)).append("\n");
    sb.append("    liveMode: ").append(toIndentedString(liveMode)).append("\n");
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("    customer: ").append(toIndentedString(customer)).append("\n");
    sb.append("    planId: ").append(toIndentedString(planId)).append("\n");
    sb.append("    plan: ").append(toIndentedString(plan)).append("\n");
    sb.append("    currentSchedule: ").append(toIndentedString(currentSchedule)).append("\n");
    sb.append("    prorate: ").append(toIndentedString(prorate)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    nextScheduleTime: ").append(toIndentedString(nextScheduleTime)).append("\n");
    sb.append("    trialStart: ").append(toIndentedString(trialStart)).append("\n");
    sb.append("    trialEnd: ").append(toIndentedString(trialEnd)).append("\n");
    sb.append("    discount: ").append(toIndentedString(discount)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    createTime: ").append(toIndentedString(createTime)).append("\n");
    sb.append("    updateTime: ").append(toIndentedString(updateTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

