/*
 * elepay API リファレンス
 * elepay APIはRESTをベースに構成された決済APIです。支払い処理、返金処理など、決済に関わる運用における様々なことができます。
 *
 * The version of the OpenAPI document: 1.2.3
 * Contact: support@elestyle.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.elepay.client.charge.pojo;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.elepay.client.charge.pojo.SubscriptionDto;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * 定期課金情報リスト
 */
@ApiModel(description = "定期課金情報リスト")
@JsonPropertyOrder({
  SubscriptionsResponse.JSON_PROPERTY_TOTAL,
  SubscriptionsResponse.JSON_PROPERTY_SUBSCRIPTIONS
})

public class SubscriptionsResponse {
  public static final String JSON_PROPERTY_TOTAL = "total";
  private Integer total;

  public static final String JSON_PROPERTY_SUBSCRIPTIONS = "subscriptions";
  private List<SubscriptionDto> subscriptions = null;


  public SubscriptionsResponse total(Integer total) {
    
    this.total = total;
    return this;
  }

   /**
   * 件数
   * @return total
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "件数")
  @JsonProperty(JSON_PROPERTY_TOTAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTotal() {
    return total;
  }


  public void setTotal(Integer total) {
    this.total = total;
  }


  public SubscriptionsResponse subscriptions(List<SubscriptionDto> subscriptions) {
    
    this.subscriptions = subscriptions;
    return this;
  }

  public SubscriptionsResponse addSubscriptionsItem(SubscriptionDto subscriptionsItem) {
    if (this.subscriptions == null) {
      this.subscriptions = new ArrayList<>();
    }
    this.subscriptions.add(subscriptionsItem);
    return this;
  }

   /**
   * 定期課金詳細情報
   * @return subscriptions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "定期課金詳細情報")
  @JsonProperty(JSON_PROPERTY_SUBSCRIPTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<SubscriptionDto> getSubscriptions() {
    return subscriptions;
  }


  public void setSubscriptions(List<SubscriptionDto> subscriptions) {
    this.subscriptions = subscriptions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubscriptionsResponse subscriptionsResponse = (SubscriptionsResponse) o;
    return Objects.equals(this.total, subscriptionsResponse.total) &&
        Objects.equals(this.subscriptions, subscriptionsResponse.subscriptions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(total, subscriptions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubscriptionsResponse {\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    subscriptions: ").append(toIndentedString(subscriptions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

