/*
 * elepay API リファレンス
 * elepay APIはRESTをベースに構成された決済APIです。支払い処理、返金処理など、決済に関わる運用における様々なことができます。
 *
 * The version of the OpenAPI document: 1.1.24
 * Contact: support@elestyle.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.elepay.client.charge.pojo;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.elepay.client.charge.pojo.SubscriptionScheduleStatusType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * 定期課金周期情報オブジェクト
 */
@ApiModel(description = "定期課金周期情報オブジェクト")
@JsonPropertyOrder({
  SubscriptionScheduleDto.JSON_PROPERTY_ID,
  SubscriptionScheduleDto.JSON_PROPERTY_OBJECT,
  SubscriptionScheduleDto.JSON_PROPERTY_AMOUNT,
  SubscriptionScheduleDto.JSON_PROPERTY_CURRENCY,
  SubscriptionScheduleDto.JSON_PROPERTY_PERIOD_START,
  SubscriptionScheduleDto.JSON_PROPERTY_PERIOD_END,
  SubscriptionScheduleDto.JSON_PROPERTY_TRIALING,
  SubscriptionScheduleDto.JSON_PROPERTY_STATUS
})

public class SubscriptionScheduleDto {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_OBJECT = "object";
  private String _object = "subscription_schedule";

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  private Integer amount;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  private String currency;

  public static final String JSON_PROPERTY_PERIOD_START = "periodStart";
  private Long periodStart;

  public static final String JSON_PROPERTY_PERIOD_END = "periodEnd";
  private Long periodEnd;

  public static final String JSON_PROPERTY_TRIALING = "trialing";
  private Boolean trialing;

  public static final String JSON_PROPERTY_STATUS = "status";
  private SubscriptionScheduleStatusType status;


  public SubscriptionScheduleDto id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Subscription Schedule ID
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Subscription Schedule ID")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public SubscriptionScheduleDto _object(String _object) {
    
    this._object = _object;
    return this;
  }

   /**
   * 対象種類の表記
   * @return _object
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "対象種類の表記")
  @JsonProperty(JSON_PROPERTY_OBJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getObject() {
    return _object;
  }


  public void setObject(String _object) {
    this._object = _object;
  }


  public SubscriptionScheduleDto amount(Integer amount) {
    
    this.amount = amount;
    return this;
  }

   /**
   * 課金金額
   * @return amount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "課金金額")
  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAmount() {
    return amount;
  }


  public void setAmount(Integer amount) {
    this.amount = amount;
  }


  public SubscriptionScheduleDto currency(String currency) {
    
    this.currency = currency;
    return this;
  }

   /**
   * 通貨コード (ISO_4217)
   * @return currency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "通貨コード (ISO_4217)")
  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCurrency() {
    return currency;
  }


  public void setCurrency(String currency) {
    this.currency = currency;
  }


  public SubscriptionScheduleDto periodStart(Long periodStart) {
    
    this.periodStart = periodStart;
    return this;
  }

   /**
   * 周期開始UTCタイムスタンプ
   * @return periodStart
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "周期開始UTCタイムスタンプ")
  @JsonProperty(JSON_PROPERTY_PERIOD_START)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getPeriodStart() {
    return periodStart;
  }


  public void setPeriodStart(Long periodStart) {
    this.periodStart = periodStart;
  }


  public SubscriptionScheduleDto periodEnd(Long periodEnd) {
    
    this.periodEnd = periodEnd;
    return this;
  }

   /**
   * 周期終了UTCタイムスタンプ
   * @return periodEnd
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "周期終了UTCタイムスタンプ")
  @JsonProperty(JSON_PROPERTY_PERIOD_END)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getPeriodEnd() {
    return periodEnd;
  }


  public void setPeriodEnd(Long periodEnd) {
    this.periodEnd = periodEnd;
  }


  public SubscriptionScheduleDto trialing(Boolean trialing) {
    
    this.trialing = trialing;
    return this;
  }

   /**
   * トライアル期間フラグ
   * @return trialing
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "トライアル期間フラグ")
  @JsonProperty(JSON_PROPERTY_TRIALING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getTrialing() {
    return trialing;
  }


  public void setTrialing(Boolean trialing) {
    this.trialing = trialing;
  }


  public SubscriptionScheduleDto status(SubscriptionScheduleStatusType status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SubscriptionScheduleStatusType getStatus() {
    return status;
  }


  public void setStatus(SubscriptionScheduleStatusType status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubscriptionScheduleDto subscriptionScheduleDto = (SubscriptionScheduleDto) o;
    return Objects.equals(this.id, subscriptionScheduleDto.id) &&
        Objects.equals(this._object, subscriptionScheduleDto._object) &&
        Objects.equals(this.amount, subscriptionScheduleDto.amount) &&
        Objects.equals(this.currency, subscriptionScheduleDto.currency) &&
        Objects.equals(this.periodStart, subscriptionScheduleDto.periodStart) &&
        Objects.equals(this.periodEnd, subscriptionScheduleDto.periodEnd) &&
        Objects.equals(this.trialing, subscriptionScheduleDto.trialing) &&
        Objects.equals(this.status, subscriptionScheduleDto.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, _object, amount, currency, periodStart, periodEnd, trialing, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubscriptionScheduleDto {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    _object: ").append(toIndentedString(_object)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    periodStart: ").append(toIndentedString(periodStart)).append("\n");
    sb.append("    periodEnd: ").append(toIndentedString(periodEnd)).append("\n");
    sb.append("    trialing: ").append(toIndentedString(trialing)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

