/*
 * elepay API リファレンス
 * elepay APIはRESTをベースに構成された決済APIです。支払い処理、返金処理など、決済に関わる運用における様々なことができます。
 *
 * The version of the OpenAPI document: 1.2.4
 * Contact: support@elestyle.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.elepay.client.charge.pojo;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.elepay.client.charge.pojo.ChargeDto;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * 定期課金周期情報オブジェクト
 */
@ApiModel(description = "定期課金周期情報オブジェクト")
@JsonPropertyOrder({
  SubscriptionPeriodDto.JSON_PROPERTY_ID,
  SubscriptionPeriodDto.JSON_PROPERTY_OBJECT,
  SubscriptionPeriodDto.JSON_PROPERTY_START_TIME,
  SubscriptionPeriodDto.JSON_PROPERTY_END_TIME,
  SubscriptionPeriodDto.JSON_PROPERTY_CHARGE
})

public class SubscriptionPeriodDto {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_OBJECT = "object";
  private String _object = "subscription_period";

  public static final String JSON_PROPERTY_START_TIME = "startTime";
  private Long startTime;

  public static final String JSON_PROPERTY_END_TIME = "endTime";
  private Long endTime;

  public static final String JSON_PROPERTY_CHARGE = "charge";
  private ChargeDto charge;


  public SubscriptionPeriodDto id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Subscription Period ID
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Subscription Period ID")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public SubscriptionPeriodDto _object(String _object) {
    
    this._object = _object;
    return this;
  }

   /**
   * 対象種類の表記
   * @return _object
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "対象種類の表記")
  @JsonProperty(JSON_PROPERTY_OBJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getObject() {
    return _object;
  }


  public void setObject(String _object) {
    this._object = _object;
  }


  public SubscriptionPeriodDto startTime(Long startTime) {
    
    this.startTime = startTime;
    return this;
  }

   /**
   * 周期開始UTCタイムスタンプ
   * @return startTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "周期開始UTCタイムスタンプ")
  @JsonProperty(JSON_PROPERTY_START_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getStartTime() {
    return startTime;
  }


  public void setStartTime(Long startTime) {
    this.startTime = startTime;
  }


  public SubscriptionPeriodDto endTime(Long endTime) {
    
    this.endTime = endTime;
    return this;
  }

   /**
   * 周期終了UTCタイムスタンプ
   * @return endTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "周期終了UTCタイムスタンプ")
  @JsonProperty(JSON_PROPERTY_END_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getEndTime() {
    return endTime;
  }


  public void setEndTime(Long endTime) {
    this.endTime = endTime;
  }


  public SubscriptionPeriodDto charge(ChargeDto charge) {
    
    this.charge = charge;
    return this;
  }

   /**
   * Get charge
   * @return charge
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CHARGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ChargeDto getCharge() {
    return charge;
  }


  public void setCharge(ChargeDto charge) {
    this.charge = charge;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubscriptionPeriodDto subscriptionPeriodDto = (SubscriptionPeriodDto) o;
    return Objects.equals(this.id, subscriptionPeriodDto.id) &&
        Objects.equals(this._object, subscriptionPeriodDto._object) &&
        Objects.equals(this.startTime, subscriptionPeriodDto.startTime) &&
        Objects.equals(this.endTime, subscriptionPeriodDto.endTime) &&
        Objects.equals(this.charge, subscriptionPeriodDto.charge);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, _object, startTime, endTime, charge);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubscriptionPeriodDto {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    _object: ").append(toIndentedString(_object)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    charge: ").append(toIndentedString(charge)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

