/*
 * elepay API リファレンス
 * elepay APIはRESTをベースに構成された決済APIです。支払い処理、返金処理など、決済に関わる運用における様々なことができます。
 *
 * The version of the OpenAPI document: 1.2.5
 * Contact: support@elestyle.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.elepay.client.charge.pojo;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.elepay.client.charge.pojo.TerminalReaderDto;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * リーダー情報リスト
 */
@JsonPropertyOrder({
  TerminalReadersResponse.JSON_PROPERTY_TOTAL,
  TerminalReadersResponse.JSON_PROPERTY_READERS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class TerminalReadersResponse {
  public static final String JSON_PROPERTY_TOTAL = "total";
  private Integer total;

  public static final String JSON_PROPERTY_READERS = "readers";
  private List<TerminalReaderDto> readers;

  public TerminalReadersResponse() {
  }

  public TerminalReadersResponse total(Integer total) {
    
    this.total = total;
    return this;
  }

   /**
   * 件数
   * @return total
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOTAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTotal() {
    return total;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotal(Integer total) {
    this.total = total;
  }


  public TerminalReadersResponse readers(List<TerminalReaderDto> readers) {
    
    this.readers = readers;
    return this;
  }

  public TerminalReadersResponse addReadersItem(TerminalReaderDto readersItem) {
    if (this.readers == null) {
      this.readers = new ArrayList<>();
    }
    this.readers.add(readersItem);
    return this;
  }

   /**
   * リーダー詳細情報
   * @return readers
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_READERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<TerminalReaderDto> getReaders() {
    return readers;
  }


  @JsonProperty(JSON_PROPERTY_READERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReaders(List<TerminalReaderDto> readers) {
    this.readers = readers;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TerminalReadersResponse terminalReadersResponse = (TerminalReadersResponse) o;
    return Objects.equals(this.total, terminalReadersResponse.total) &&
        Objects.equals(this.readers, terminalReadersResponse.readers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(total, readers);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TerminalReadersResponse {\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    readers: ").append(toIndentedString(readers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `total` to the URL query string
    if (getTotal() != null) {
      try {
        joiner.add(String.format("%stotal%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getTotal()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `readers` to the URL query string
    if (getReaders() != null) {
      for (int i = 0; i < getReaders().size(); i++) {
        if (getReaders().get(i) != null) {
          joiner.add(getReaders().get(i).toUrlQueryString(String.format("%sreaders%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }

}

