/*
 * elepay API リファレンス
 * elepay APIはRESTをベースに構成された決済APIです。支払い処理、返金処理など、決済に関わる運用における様々なことができます。
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: support@elestyle.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.elepay.client.charge.pojo;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.elepay.client.charge.pojo.AddressDto;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AddressTransliterationDto
 */
public class AddressTransliterationDtoTest {
    private final AddressTransliterationDto model = new AddressTransliterationDto();

    /**
     * Model tests for AddressTransliterationDto
     */
    @Test
    public void testAddressTransliterationDto() {
        // TODO: test AddressTransliterationDto
    }

    /**
     * Test the property 'kanji'
     */
    @Test
    public void kanjiTest() {
        // TODO: test kanji
    }

    /**
     * Test the property 'kana'
     */
    @Test
    public void kanaTest() {
        // TODO: test kana
    }

    /**
     * Test the property 'romaji'
     */
    @Test
    public void romajiTest() {
        // TODO: test romaji
    }

}
