/*
 * elepay API リファレンス
 * elepay APIはRESTをベースに構成された決済APIです。支払い処理、返金処理など、決済に関わる運用における様々なことができます。
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: support@elestyle.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.elepay.client.charge.pojo;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.elepay.client.charge.pojo.ChargeDto;
import io.elepay.client.charge.pojo.CodeItem;
import io.elepay.client.charge.pojo.CodeStatusType;
import io.elepay.client.charge.pojo.CustomerDto;
import io.elepay.client.charge.pojo.InvoiceDto;
import io.elepay.client.charge.pojo.SourceDto;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CodeDto
 */
public class CodeDtoTest {
    private final CodeDto model = new CodeDto();

    /**
     * Model tests for CodeDto
     */
    @Test
    public void testCodeDto() {
        // TODO: test CodeDto
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property '_object'
     */
    @Test
    public void _objectTest() {
        // TODO: test _object
    }

    /**
     * Test the property 'liveMode'
     */
    @Test
    public void liveModeTest() {
        // TODO: test liveMode
    }

    /**
     * Test the property 'codeUrl'
     */
    @Test
    public void codeUrlTest() {
        // TODO: test codeUrl
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'orderNo'
     */
    @Test
    public void orderNoTest() {
        // TODO: test orderNo
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'extra'
     */
    @Test
    public void extraTest() {
        // TODO: test extra
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'charge'
     */
    @Test
    public void chargeTest() {
        // TODO: test charge
    }

    /**
     * Test the property 'customer'
     */
    @Test
    public void customerTest() {
        // TODO: test customer
    }

    /**
     * Test the property 'source'
     */
    @Test
    public void sourceTest() {
        // TODO: test source
    }

    /**
     * Test the property 'frontUrl'
     */
    @Test
    public void frontUrlTest() {
        // TODO: test frontUrl
    }

    /**
     * Test the property 'items'
     */
    @Test
    public void itemsTest() {
        // TODO: test items
    }

    /**
     * Test the property 'locationId'
     */
    @Test
    public void locationIdTest() {
        // TODO: test locationId
    }

    /**
     * Test the property 'expired'
     */
    @Test
    public void expiredTest() {
        // TODO: test expired
    }

    /**
     * Test the property 'expiryTime'
     */
    @Test
    public void expiryTimeTest() {
        // TODO: test expiryTime
    }

    /**
     * Test the property 'expiryPeriod'
     */
    @Test
    public void expiryPeriodTest() {
        // TODO: test expiryPeriod
    }

    /**
     * Test the property 'createTime'
     */
    @Test
    public void createTimeTest() {
        // TODO: test createTime
    }

    /**
     * Test the property 'shouldCreateSource'
     */
    @Test
    public void shouldCreateSourceTest() {
        // TODO: test shouldCreateSource
    }

    /**
     * Test the property 'activeSources'
     */
    @Test
    public void activeSourcesTest() {
        // TODO: test activeSources
    }

    /**
     * Test the property 'invoice'
     */
    @Test
    public void invoiceTest() {
        // TODO: test invoice
    }

}
