/*
 * elepay API リファレンス
 * elepay APIはRESTをベースに構成された決済APIです。支払い処理、返金処理など、決済に関わる運用における様々なことができます。
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: support@elestyle.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.elepay.client.charge.pojo;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.elepay.client.charge.pojo.TaxRateType;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InvoiceTaxSummaryItemDto
 */
public class InvoiceTaxSummaryItemDtoTest {
    private final InvoiceTaxSummaryItemDto model = new InvoiceTaxSummaryItemDto();

    /**
     * Model tests for InvoiceTaxSummaryItemDto
     */
    @Test
    public void testInvoiceTaxSummaryItemDto() {
        // TODO: test InvoiceTaxSummaryItemDto
    }

    /**
     * Test the property 'taxRateType'
     */
    @Test
    public void taxRateTypeTest() {
        // TODO: test taxRateType
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'tax'
     */
    @Test
    public void taxTest() {
        // TODO: test tax
    }

}
